tft_level_odds = {
    1: [100, 0, 0, 0, 0],
    2: [100, 0, 0, 0, 0],
    3: [70, 30, 0, 0, 0],
    4: [45, 33, 22, 0, 0],
    5: [30, 33, 27, 10, 0],
    6: [19, 30, 35, 15, 1],
    7: [15, 25, 35, 20, 5],
    8: [10, 15, 30, 30, 15],
    9: [5, 10, 15, 30, 40],
    10: [0, 0, 10, 45, 45]
}

# Don't mind this, just a list of all the units in the game for the current set
# units = [
#     ("Ahri", "4"),
#     ("Amumu", "3"),
#     ("Annie", "1"),
#     ("Aphelios", "2"),
#     ("Bard", "2"),
#     ("Blitzcrank", "4"),
#     ("Caitlyn", "4"),
#     ("Corki", "1"),
#     ("Ekko", "3"),
#     ("Evelynn", "1"),
#     ("Ezreal", "4"),
#     ("Garen", "2"),
#     ("Gnar", "2"),
#     ("Gragas", "2"),
#     ("Illaoi", "5"),
#     ("Jax", "2"),
#     ("Jhin", "5"),
#     ("Jinx", "1"),
#     ("K'Sante", "1"),
#     ("Kai'Sa", "2"),
#     ("Karthus", "4"),
#     ("Katarina", "2"),
#     ("Kayle", "2"),
#     ("Kayn", "5"),
#     ("Akali (KDA)", "4"),
#     ("Kennen", "1"),
#     ("Lillia", "1"),
#     ("Lucian", "5"),
#     ("Lulu", "3"),
#     ("Lux", "3"),
#     ("Miss Fortune", "5"),
#     ("Mordekaiser", "3"),
#     ("Nami", "1"),
#     ("Neeko", "3"),
#     ("Olaf", "1"),
#     ("Pantheon", "2"),
#     ("Poppy", "4"),
#     ("Qiyana", "5"),
#     ("Riven", "3"),
#     ("Samira", "3"),
#     ("Senna", "2"),
#     ("Seraphine", "2"),
#     ("Sett", "3"),
#     ("Sona", "5"),
#     ("Tahm Kench", "1"),
#     ("Taric", "1"),
#     ("Akali (TD)", "4"),
#     ("Thresh", "4"),
#     ("Twisted Fate", "4"),
#     ("Twitch", "2"),
#     ("Urgot", "3"),
#     ("Vex", "3"),
#     ("Vi", "1"),
#     ("Viego", "4"),
#     ("Yasuo", "1"),
#     ("Yone", "3"),
#     ("Yorick", "5"),
#     ("Zac", "4"),
#     ("Zed", "4"),
#     ("Ziggs", "5"),
# ]